--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Members_notification; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public."Members_notification" (
    id bigint NOT NULL,
    message text NOT NULL,
    date_notified timestamp with time zone NOT NULL
);


ALTER TABLE public."Members_notification" OWNER TO aga;

--
-- Name: Members_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public."Members_notification" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Members_notification_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Members_paymentcodes; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public."Members_paymentcodes" (
    id bigint NOT NULL,
    code character varying(150) NOT NULL,
    amount integer NOT NULL
);


ALTER TABLE public."Members_paymentcodes" OWNER TO aga;

--
-- Name: Members_paymentcodes_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public."Members_paymentcodes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Members_paymentcodes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO aga;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO aga;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.cart (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    video_name character varying(150) NOT NULL,
    cartegory character varying(150) NOT NULL,
    image_url character varying(200) NOT NULL,
    price integer NOT NULL,
    season character varying(100) NOT NULL,
    type character varying(100) NOT NULL
);


ALTER TABLE public.cart OWNER TO aga;

--
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartegories; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.cartegories (
    "cartId" bigint NOT NULL,
    "cartName" character varying(50) NOT NULL
);


ALTER TABLE public.cartegories OWNER TO aga;

--
-- Name: cartegories_cartId_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.cartegories ALTER COLUMN "cartId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."cartegories_cartId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposit; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.deposit (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    amount integer NOT NULL,
    "time" timestamp with time zone NOT NULL
);


ALTER TABLE public.deposit OWNER TO aga;

--
-- Name: deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO aga;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO aga;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO aga;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO aga;

--
-- Name: downloads; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.downloads (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    video_name character varying(150) NOT NULL,
    cost character varying(150) NOT NULL,
    "time" timestamp with time zone NOT NULL
);


ALTER TABLE public.downloads OWNER TO aga;

--
-- Name: downloads_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.downloads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.downloads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    username character varying(100) NOT NULL
);


ALTER TABLE public.members OWNER TO aga;

--
-- Name: members_groups; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.members_groups (
    id bigint NOT NULL,
    members_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.members_groups OWNER TO aga;

--
-- Name: members_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.members_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_user_permissions; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.members_user_permissions (
    id bigint NOT NULL,
    members_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.members_user_permissions OWNER TO aga;

--
-- Name: members_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.members_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.messages (
    message_id bigint NOT NULL,
    email character varying(100) NOT NULL,
    message text NOT NULL
);


ALTER TABLE public.messages OWNER TO aga;

--
-- Name: messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.messages ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multimedia_awaitingactivation; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.multimedia_awaitingactivation (
    id bigint NOT NULL,
    video_name character varying(100) NOT NULL,
    price integer NOT NULL,
    date_entered timestamp with time zone NOT NULL,
    username character varying(100) NOT NULL
);


ALTER TABLE public.multimedia_awaitingactivation OWNER TO aga;

--
-- Name: multimedia_awaitingactivation_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.multimedia_awaitingactivation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multimedia_awaitingactivation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multimedia_like; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.multimedia_like (
    id bigint NOT NULL,
    "user" character varying(150) NOT NULL,
    total_like integer NOT NULL,
    video_title_id bigint NOT NULL
);


ALTER TABLE public.multimedia_like OWNER TO aga;

--
-- Name: multimedia_like_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.multimedia_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multimedia_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multimedia_review; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.multimedia_review (
    id bigint NOT NULL,
    "user" character varying(150) NOT NULL,
    rate integer NOT NULL,
    comment text NOT NULL,
    video_title_id bigint NOT NULL
);


ALTER TABLE public.multimedia_review OWNER TO aga;

--
-- Name: multimedia_review_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.multimedia_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multimedia_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    phone_number character varying(150) NOT NULL,
    "payment_Suc" boolean NOT NULL
);


ALTER TABLE public.payments OWNER TO aga;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchased; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.purchased (
    id bigint NOT NULL,
    username character varying(150) NOT NULL,
    video_name character varying(150) NOT NULL,
    image_url character varying(200) NOT NULL,
    price integer NOT NULL,
    purchase_time date NOT NULL
);


ALTER TABLE public.purchased OWNER TO aga;

--
-- Name: purchased_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.purchased ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchased_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO aga;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO aga;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploads; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.uploads (
    "vidId" bigint NOT NULL,
    title character varying(100) NOT NULL,
    price integer NOT NULL,
    typs character varying(150) NOT NULL,
    synopsis text NOT NULL,
    date_uploaded timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    size character varying(100) NOT NULL,
    season character varying(150) NOT NULL,
    popular boolean NOT NULL,
    cartegory_id character varying(50) NOT NULL
);


ALTER TABLE public.uploads OWNER TO aga;

--
-- Name: uploads_vidId_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.uploads ALTER COLUMN "vidId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."uploads_vidId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: videos; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.videos (
    "videoId" bigint NOT NULL,
    name character varying(200) NOT NULL,
    video character varying(100) NOT NULL,
    quality character varying(100) NOT NULL
);


ALTER TABLE public.videos OWNER TO aga;

--
-- Name: videos_videoId_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.videos ALTER COLUMN "videoId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."videos_videoId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: watch; Type: TABLE; Schema: public; Owner: aga
--

CREATE TABLE public.watch (
    id bigint NOT NULL,
    video_name character varying(150) NOT NULL,
    watcher character varying(150) NOT NULL,
    image_url character varying(200) NOT NULL
);


ALTER TABLE public.watch OWNER TO aga;

--
-- Name: watch_id_seq; Type: SEQUENCE; Schema: public; Owner: aga
--

ALTER TABLE public.watch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Members_notification; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public."Members_notification" (id, message, date_notified) FROM stdin;
\.


--
-- Data for Name: Members_paymentcodes; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public."Members_paymentcodes" (id, code, amount) FROM stdin;
1	TCG4WWSBIS	1
2	TCG7WZMSNR	1
3	TCG6X05OSQ	1
4	TCG2X0UGFI	1
5	TCG6X10DC2	1
6	TCG4X1U244	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.cart (id, username, video_name, cartegory, image_url, price, season, type) FROM stdin;
2	seller	Trial2	cartegory	https://images.unsplash.com/photo-1604545200457-63641121af3b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGRhcmVkZXZpbHxlbnwwfHwwfHx8MA%3D%3D	0	full	type
\.


--
-- Data for Name: cartegories; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.cartegories ("cartId", "cartName") FROM stdin;
1	ninja
\.


--
-- Data for Name: deposit; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.deposit (id, name, amount, "time") FROM stdin;
1	seller	1	2025-03-11 21:37:01.243211+00
2	seller	1	2025-03-11 22:09:30.110016+00
3	seller	1	2025-03-12 13:38:07.812064+00
4	seller	1	2025-03-12 13:40:15.549948+00
5	seller	1	2025-03-12 13:41:15.560773+00
6	seller	1	2025-03-12 13:47:49.444295+00
7	seller	1	2025-03-16 12:25:20.582213+00
8	seller	1	2025-03-16 12:43:53.887322+00
9	seller	1	2025-03-16 12:47:21.407814+00
10	seller	1	2025-03-16 12:51:50.598503+00
11	seller	1	2025-03-16 12:52:56.353831+00
12	seller	1	2025-03-16 12:58:13.298171+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
4	2025-03-11 17:38:13.273955+00	1	seller	2	[{"changed": {"fields": ["Account(Ksh)"]}}]	19	2
5	2025-03-11 19:50:55.504556+00	3	Trial3	1	[{"added": {}}]	9	2
6	2025-03-11 19:51:58.518394+00	4	Trial4	1	[{"added": {}}]	9	2
7	2025-03-11 21:45:15.540767+00	1	seller	2	[{"changed": {"fields": ["Account(Ksh)"]}}]	19	2
8	2025-03-11 21:45:51.731151+00	4	seller	3		16	2
9	2025-03-11 22:04:03.575658+00	2	AwaitingActivation object (2)	3		21	2
10	2025-03-11 22:04:12.619726+00	1	AwaitingActivation object (1)	3		21	2
11	2025-03-12 13:45:18.970752+00	5	Trial5	2	[{"changed": {"fields": ["Price"]}}]	9	2
12	2025-03-12 13:46:02.756974+00	5	seller	3		16	2
17	2025-03-16 12:33:21.770091+00	5	Trial5	2	[{"changed": {"fields": ["Price"]}}]	9	2
18	2025-03-16 12:54:24.641437+00	8	seller	3		16	2
19	2025-03-16 12:54:24.641534+00	7	seller	3		16	2
20	2025-03-16 12:59:48.462247+00	1	seller	2	[{"changed": {"fields": ["Account(Ksh)"]}}]	19	2
23	2025-03-27 07:54:45.998126+00	9	seller1	2	[{"changed": {"fields": ["Watcher"]}}]	16	2
24	2025-03-27 09:15:55.298047+00	2	seller	2	[{"changed": {"fields": ["Username"]}}]	11	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	contenttypes	contenttype
2	auth	permission
3	auth	group
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
48	contenttypes	0001_initial	2025-03-27 10:16:04.108654+00
49	contenttypes	0002_remove_content_type_name	2025-03-27 10:16:04.192784+00
50	auth	0001_initial	2025-03-27 10:21:23.003103+00
51	auth	0002_alter_permission_name_max_length	2025-03-27 10:21:23.022734+00
52	auth	0003_alter_user_email_max_length	2025-03-27 10:21:23.030863+00
53	auth	0004_alter_user_username_opts	2025-03-27 10:21:23.039418+00
54	auth	0005_alter_user_last_login_null	2025-03-27 10:21:23.047628+00
55	auth	0006_require_contenttypes_0002	2025-03-27 10:21:23.055866+00
56	auth	0007_alter_validators_add_error_messages	2025-03-27 10:21:23.064184+00
57	auth	0008_alter_user_username_max_length	2025-03-27 10:21:23.072599+00
58	auth	0009_alter_user_last_name_max_length	2025-03-27 10:21:23.080599+00
59	auth	0010_alter_group_name_max_length	2025-03-27 10:21:23.089048+00
60	auth	0011_update_proxy_permissions	2025-03-27 10:21:23.097391+00
61	auth	0012_alter_user_first_name_max_length	2025-03-27 10:21:23.105614+00
62	multimedia	0001_initial	2025-03-27 10:22:32.379541+00
63	multimedia	0002_awaitingactivation	2025-03-27 10:22:32.42696+00
64	multimedia	0003_awaitingactivation_username	2025-03-27 10:22:32.460063+00
65	multimedia	0004_like_review_remove_homepagevideo_videoname_and_more	2025-03-27 10:22:32.46822+00
66	multimedia	0005_remove_videoupload_quality_and_more	2025-03-27 10:22:32.476905+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
firz7qobew8us74mszn0a2qzp5lzato0	.eJxVjEEOgjAQRe_StWmc0jLg0j1nINOZjqCmTSisjHdXEha6_e-9_zIjbes0bjUt4yzmYpw5_W6R-JHyDuRO-VYsl7wuc7S7Yg9a7VAkPa-H-3cwUZ2-dYcRvLBrkanvGmpCgN6JIrHH5BWkCXom75iBAYL2yhpbJURyraB5fwDn1Dhl:1ts29C:IwvmPf-4Ig9W20AAm_oY6LYrQ0n2FhIel1NUn1uOYjM	2025-03-25 16:08:02.847327+00
p82f0km136wu9tiv7149mwbj6i9qpvv9	.eJxVjEEOgjAQRe_StWmc0jLg0j1nINOZjqCmTSisjHdXEha6_e-9_zIjbes0bjUt4yzmYpw5_W6R-JHyDuRO-VYsl7wuc7S7Yg9a7VAkPa-H-3cwUZ2-dYcRvLBrkanvGmpCgN6JIrHH5BWkCXom75iBAYL2yhpbJURyraB5fwDn1Dhl:1ts7BN:nUuI3eve4LEInDYGIic5yc2AmcpjjtvrPl_1Ad5084I	2025-03-25 21:30:37.082164+00
4wt8x81ybglgwusr0wirazxwmpn33clf	.eJxVjMsOwiAQRf-FtSFShkdduu83kGEGpGogKe3K-O_apAvd3nPOfYmA21rC1tMSZhYXocTpd4tIj1R3wHestyap1XWZo9wVedAup8bpeT3cv4OCvXxrIESfSZlBIfvMkQmcU9pra_SYLBJ7sIAO8oCWtIljPtscyWeICEa8P_54OJc:1tsG2n:rgeIOeXb92NeQVIsfrCIC7IvpNFfx9O7Y1F2EFrEI7Q	2025-03-26 06:58:21.071983+00
6l3sd0mjgrxh90y8tvequ4qye6gmnbwx	.eJxVjEEOgjAQRe_StWmc0jLg0j1nINOZjqCmTSisjHdXEha6_e-9_zIjbes0bjUt4yzmYpw5_W6R-JHyDuRO-VYsl7wuc7S7Yg9a7VAkPa-H-3cwUZ2-dYcRvLBrkanvGmpCgN6JIrHH5BWkCXom75iBAYL2yhpbJURyraB5fwDn1Dhl:1ttmsG:GDXBAMmgy7-fcJOCNnSObff9n7uoY1fPHmu3UsQI8L0	2025-03-30 12:13:48.353279+00
yv7eg7f7g6q5lznxvq6y3oc0dmw0y3d5	.eJxVjEEOgjAQRe_StWmc0jLg0j1nINOZjqCmTSisjHdXEha6_e-9_zIjbes0bjUt4yzmYpw5_W6R-JHyDuRO-VYsl7wuc7S7Yg9a7VAkPa-H-3cwUZ2-dYcRvLBrkanvGmpCgN6JIrHH5BWkCXom75iBAYL2yhpbJURyraB5fwDn1Dhl:1ttmx4:s7Ac3EXUUEoaB7YnteMJ_uejby3TmZwyLO_8xMF8CtU	2025-03-30 12:18:46.216643+00
dpdrg81hsitc3kbxs05xouh9tpe432ia	e30:1txQoj:cTFvwJX2UazAx6bK9-EVc5Mfw42g0WmWCO8N2mCPQTo	2025-04-09 13:29:13.332976+00
7jsvp3k4hc0jf7iu3hwprqrms0qsweag	e30:1txQr2:K7lShtAhjoBI1ZE5QcKuSwjvDItaFfTiawRaRUo-GOY	2025-04-09 13:31:36.425246+00
lvkc7g6nvw6sxxvw623o89zzrp62ocy2	.eJxVjEEOgjAQRe_StWmc0jLg0j1nINOZjqCmTSisjHdXEha6_e-9_zIjbes0bjUt4yzmYpw5_W6R-JHyDuRO-VYsl7wuc7S7Yg9a7VAkPa-H-3cwUZ2-dYcRvLBrkanvGmpCgN6JIrHH5BWkCXom75iBAYL2yhpbJURyraB5fwDn1Dhl:1txRAz:xJ_3vfJ8FFlwFRqfFiBF0LddwNjONeRJGLwMOTPgHzM	2025-04-09 13:52:13.34483+00
\.


--
-- Data for Name: downloads; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.downloads (id, name, video_name, cost, "time") FROM stdin;
\.


--
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.members (id, password, last_login, is_superuser, email, is_staff, is_active, date_joined, first_name, last_name, username) FROM stdin;
3	pbkdf2_sha256$870000$QfazCce9yQswFzBogzxo9g$Uz2wWwD/ri5uBLmvfVTFeSk1b7/VLwsZF5yh7J0OmBE=	\N	f	info@gmail.com	f	t	2025-03-26 14:09:14.898696+00			info
2	pbkdf2_sha256$870000$7YKm0lRconsiw4Vde8VzNL$dzdZXiUP4+YYe8zANUbW22eSewjQ+tVHOs8F0Olw22c=	2025-03-26 13:52:13+00	t	seller@gmail.com	t	t	2025-03-11 16:05:10+00			seller
4	pbkdf2_sha256$870000$yl8uo4zfKHPgBaFSqWJyf1$SVunftqFWXxrkzfTeL658puzzDoVejbKclHG8AwIFnE=	\N	f	aga@gmail.com	f	t	2025-03-27 10:09:07.070626+00			aga
5	pbkdf2_sha256$870000$UdkYo3DqNQW3j2IgL1MyuJ$ZSwkZVprXt8Id+fRvdATx89SLjDbzVceTy487ZT5KNQ=	\N	f	aga1@gmail.com	f	t	2025-03-27 10:09:49.78859+00			aga1
6	pbkdf2_sha256$870000$2Vtz1qBZfcu6t0pH4f4wzr$VU7BT6k9ef07b2sc1MFK0/8xuG9FE4LzpIjtclPEfOA=	\N	f	aga2@gmail.com	f	t	2025-03-27 10:10:26.519107+00			aga2
\.


--
-- Data for Name: members_groups; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.members_groups (id, members_id, group_id) FROM stdin;
\.


--
-- Data for Name: members_user_permissions; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.members_user_permissions (id, members_id, permission_id) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.messages (message_id, email, message) FROM stdin;
\.


--
-- Data for Name: multimedia_awaitingactivation; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.multimedia_awaitingactivation (id, video_name, price, date_entered, username) FROM stdin;
\.


--
-- Data for Name: multimedia_like; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.multimedia_like (id, "user", total_like, video_title_id) FROM stdin;
\.


--
-- Data for Name: multimedia_review; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.multimedia_review (id, "user", rate, comment, video_title_id) FROM stdin;
1	Aga254	1	best	3
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.payments (id, username, phone_number, "payment_Suc") FROM stdin;
\.


--
-- Data for Name: purchased; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.purchased (id, username, video_name, image_url, price, purchase_time) FROM stdin;
1	seller	trial6	https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1025&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D	1	2025-03-27
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzMxOTEzMCwiaWF0IjoxNzQyOTk5MTMwLCJqdGkiOiIwNjBjZTNjMDZjYzY0ZDViYWI4NjBiZmFlMTM2ZGM3MyIsInVzZXJfaWQiOjN9.3VDCSqtkrcmMMf3o0UC36gFrUmo2Hg-o-0KBXSTDBBk	2025-03-26 14:25:30.650035+00	2025-05-15 14:25:30+00	3	060ce3c06cc64d5bab860bfae136dc73
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzM4Mjg5NCwiaWF0IjoxNzQzMDYyODk0LCJqdGkiOiI4Y2ExMzhmYTM2NzY0ZTViODFlMGVjMTIwMTkzOTY5OSIsInVzZXJfaWQiOjJ9.0pF0PtJHwNTa8TTzBDKAyn2G2Pfj4-T6HLRZW1heiEY	2025-03-27 08:08:14.040464+00	2025-05-16 08:08:14+00	2	8ca138fa36764e5b81e0ec1201939699
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzM4MzQ4OCwiaWF0IjoxNzQzMDYzNDg4LCJqdGkiOiJmMmQ2OGVkYjNiZGE0YWViODA1ZWMwNWJiYWI4MDI0OSIsInVzZXJfaWQiOjJ9.1QdbQUPXjobVsKaAXIPC7vfFopDTsy-HWSvRwgkCDNw	2025-03-27 08:18:08.094904+00	2025-05-16 08:18:08+00	2	f2d68edb3bda4aeb805ec05bbab80249
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzM4NDYyMSwiaWF0IjoxNzQzMDY0NjIxLCJqdGkiOiJkNTU5ODdkOTAyOGY0ZjRiOTU0NTJkM2NiYjI4OWQzNiIsInVzZXJfaWQiOjJ9.dN2Ud8tXcbk_rW0fGMf8iPyOoN25nmmfNphptxcowHU	2025-03-27 08:37:01.713739+00	2025-05-16 08:37:01+00	2	d55987d9028f4f4b95452d3cbb289d36
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzM4NTAwNiwiaWF0IjoxNzQzMDY1MDA2LCJqdGkiOiIxMTJjN2E1MDAzZDQ0OWZjOGZlNWZmYjRiNDYwMmM1MyIsInVzZXJfaWQiOjJ9.0hQdN7AJIki8VlrbgfMjUm1VsYiL0sjm7m5GsIn--AE	2025-03-27 08:43:26.516511+00	2025-05-16 08:43:26+00	2	112c7a5003d449fc8fe5ffb4b4602c53
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzM4NTM1MSwiaWF0IjoxNzQzMDY1MzUxLCJqdGkiOiJkMTkzNDIzZmMxZTI0YmE2YjYwZjBmMThhZDRiYWFlZiIsInVzZXJfaWQiOjJ9.1v0-se0R62Dc7NdvckCBTKorZHLrD-nixpUJbQeiSPM	2025-03-27 08:49:11.157542+00	2025-05-16 08:49:11+00	2	d193423fc1e24ba6b60f0f18ad4baaef
\.


--
-- Data for Name: uploads; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.uploads ("vidId", title, price, typs, synopsis, date_uploaded, image, size, season, popular, cartegory_id) FROM stdin;
1	Trial	10	movies	nothing	2025-03-11 16:07:14.353036+00	videoImage/davide-boscolo-gz9njd0zYbQ-unsplash.jpeg	0mb	season 2	t	ninja
2	Trial2	10	series	type="video/mp4"type="video/mp4"	2025-03-11 18:15:44.271687+00	videoImage/dom-hill-nimElTcTNyY-unsplash.jpeg	0mb	season 2	t	ninja
3	Trial3	10	movies	nothing	2025-03-11 19:50:54.93936+00	videoImage/kari-shea-1SAnrIxw5OY-unsplash.jpeg	0mb	season 2	f	ninja
4	Trial4	12	movies	o	2025-03-11 19:51:58.242244+00	videoImage/em-be-khoc-nhe-2dF1uCJKnNg-unsplash.jpeg	0mb	season 2	f	ninja
6	Trail6	1	movies	tyhr	2025-03-12 19:17:14.348623+00	videoImage/davide-boscolo-gz9njd0zYbQ-unsplash_VJnTioG.jpeg	0mb	season 2	f	ninja
5	Trial5	2	movies	hello	2025-03-11 20:52:54.315682+00	videoImage/bruno-cervera-8CgP-BuCU6g-unsplash.jpeg	0mb	season 2	t	ninja
\.


--
-- Data for Name: videos; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.videos ("videoId", name, video, quality) FROM stdin;
1	Trial	videos/NIMEPENDA_REMIX_-_Guardian_Angel__.x._Deus_Derrick_ft._Sammy_G_x-h5JkK4nss.f251.webm	720p
2	Trial2	videos/NIMEPENDA_REMIX_-_Guardian_Angel___9B50GMI.x._Deus_Derrick_ft._Sammy_G_x-h5JkK4nss.f251.webm	720p
3	Trial5	videos/NIMEPENDA_REMIX_-_Guardian_Angel__.x._Deus_Derrick_ft._Sammy_G_x-h5JkK4nss.f251_1.webm	720p
4	Trial6	videos/NIMEPENDA_REMIX_-_Guardian_Angel___qkhIKn1.x._Deus_Derrick_ft._Sammy_G_x-h5JkK4nss.f251.webm	720p
5	Trial6	videos/NIMEPENDA_REMIX_-_Guardian_Angel___9gjLiGB.x._Deus_Derrick_ft._Sammy_G_x-h5JkK4nss.f251.webm	720p
\.


--
-- Data for Name: watch; Type: TABLE DATA; Schema: public; Owner: aga
--

COPY public.watch (id, video_name, watcher, image_url) FROM stdin;
10	Trail6	seller	https://images.unsplash.com/photo-1604545200457-63641121af3b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGRhcmVkZXZpbHxlbnwwfHwwfHx8MA%3D%3D
9	Trial5	seller1	https://images.unsplash.com/photo-1604545200457-63641121af3b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGRhcmVkZXZpbHxlbnwwfHwwfHx8MA%3D%3D
\.


--
-- Name: Members_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public."Members_notification_id_seq"', 1, false);


--
-- Name: Members_paymentcodes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public."Members_paymentcodes_id_seq"', 6, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.cart_id_seq', 2, true);


--
-- Name: cartegories_cartId_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public."cartegories_cartId_seq"', 1, true);


--
-- Name: deposit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.deposit_id_seq', 12, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 24, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 3, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 66, true);


--
-- Name: downloads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.downloads_id_seq', 1, false);


--
-- Name: members_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.members_groups_id_seq', 1, false);


--
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.members_id_seq', 6, true);


--
-- Name: members_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.members_user_permissions_id_seq', 1, false);


--
-- Name: messages_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.messages_message_id_seq', 1, false);


--
-- Name: multimedia_awaitingactivation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.multimedia_awaitingactivation_id_seq', 8, true);


--
-- Name: multimedia_like_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.multimedia_like_id_seq', 1, false);


--
-- Name: multimedia_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.multimedia_review_id_seq', 1, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.payments_id_seq', 14, true);


--
-- Name: purchased_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.purchased_id_seq', 1, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 6, true);


--
-- Name: uploads_vidId_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public."uploads_vidId_seq"', 6, true);


--
-- Name: videos_videoId_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public."videos_videoId_seq"', 5, true);


--
-- Name: watch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aga
--

SELECT pg_catalog.setval('public.watch_id_seq', 10, true);


--
-- Name: Members_notification Members_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public."Members_notification"
    ADD CONSTRAINT "Members_notification_pkey" PRIMARY KEY (id);


--
-- Name: Members_paymentcodes Members_paymentcodes_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public."Members_paymentcodes"
    ADD CONSTRAINT "Members_paymentcodes_pkey" PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- Name: cartegories cartegories_cartName_key; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.cartegories
    ADD CONSTRAINT "cartegories_cartName_key" UNIQUE ("cartName");


--
-- Name: cartegories cartegories_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.cartegories
    ADD CONSTRAINT cartegories_pkey PRIMARY KEY ("cartId");


--
-- Name: deposit deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.deposit
    ADD CONSTRAINT deposit_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: downloads downloads_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.downloads
    ADD CONSTRAINT downloads_pkey PRIMARY KEY (id);


--
-- Name: members members_email_key; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_email_key UNIQUE (email);


--
-- Name: members_groups members_groups_members_id_group_id_d75713f1_uniq; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_groups
    ADD CONSTRAINT members_groups_members_id_group_id_d75713f1_uniq UNIQUE (members_id, group_id);


--
-- Name: members_groups members_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_groups
    ADD CONSTRAINT members_groups_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: members_user_permissions members_user_permissions_members_id_permission_id_09b1417d_uniq; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_user_permissions
    ADD CONSTRAINT members_user_permissions_members_id_permission_id_09b1417d_uniq UNIQUE (members_id, permission_id);


--
-- Name: members_user_permissions members_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_user_permissions
    ADD CONSTRAINT members_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (message_id);


--
-- Name: multimedia_awaitingactivation multimedia_awaitingactivation_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.multimedia_awaitingactivation
    ADD CONSTRAINT multimedia_awaitingactivation_pkey PRIMARY KEY (id);


--
-- Name: multimedia_like multimedia_like_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.multimedia_like
    ADD CONSTRAINT multimedia_like_pkey PRIMARY KEY (id);


--
-- Name: multimedia_review multimedia_review_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.multimedia_review
    ADD CONSTRAINT multimedia_review_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: purchased purchased_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.purchased
    ADD CONSTRAINT purchased_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: uploads uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_pkey PRIMARY KEY ("vidId");


--
-- Name: uploads uploads_title_key; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_title_key UNIQUE (title);


--
-- Name: videos videos_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY ("videoId");


--
-- Name: watch watch_pkey; Type: CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.watch
    ADD CONSTRAINT watch_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: cartegories_cartName_fa1f935f_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX "cartegories_cartName_fa1f935f_like" ON public.cartegories USING btree ("cartName" varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: members_email_7473dabd_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX members_email_7473dabd_like ON public.members USING btree (email varchar_pattern_ops);


--
-- Name: members_groups_group_id_d6e7d866; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX members_groups_group_id_d6e7d866 ON public.members_groups USING btree (group_id);


--
-- Name: members_groups_members_id_f8092160; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX members_groups_members_id_f8092160 ON public.members_groups USING btree (members_id);


--
-- Name: members_user_permissions_members_id_bdcf3c0c; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX members_user_permissions_members_id_bdcf3c0c ON public.members_user_permissions USING btree (members_id);


--
-- Name: members_user_permissions_permission_id_2c4b7274; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX members_user_permissions_permission_id_2c4b7274 ON public.members_user_permissions USING btree (permission_id);


--
-- Name: multimedia_like_video_title_id_d279547c; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX multimedia_like_video_title_id_d279547c ON public.multimedia_like USING btree (video_title_id);


--
-- Name: multimedia_review_video_title_id_afbdeefd; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX multimedia_review_video_title_id_afbdeefd ON public.multimedia_review USING btree (video_title_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: uploads_cartegory_id_8cad4e6a; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX uploads_cartegory_id_8cad4e6a ON public.uploads USING btree (cartegory_id);


--
-- Name: uploads_cartegory_id_8cad4e6a_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX uploads_cartegory_id_8cad4e6a_like ON public.uploads USING btree (cartegory_id varchar_pattern_ops);


--
-- Name: uploads_title_286cb07c_like; Type: INDEX; Schema: public; Owner: aga
--

CREATE INDEX uploads_title_286cb07c_like ON public.uploads USING btree (title varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_members_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_members_id FOREIGN KEY (user_id) REFERENCES public.members(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_groups members_groups_group_id_d6e7d866_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_groups
    ADD CONSTRAINT members_groups_group_id_d6e7d866_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_groups members_groups_members_id_f8092160_fk_members_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_groups
    ADD CONSTRAINT members_groups_members_id_f8092160_fk_members_id FOREIGN KEY (members_id) REFERENCES public.members(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_user_permissions members_user_permissions_members_id_bdcf3c0c_fk_members_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.members_user_permissions
    ADD CONSTRAINT members_user_permissions_members_id_bdcf3c0c_fk_members_id FOREIGN KEY (members_id) REFERENCES public.members(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: multimedia_like multimedia_like_video_title_id_d279547c_fk_uploads_vidId; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.multimedia_like
    ADD CONSTRAINT "multimedia_like_video_title_id_d279547c_fk_uploads_vidId" FOREIGN KEY (video_title_id) REFERENCES public.uploads("vidId") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: multimedia_review multimedia_review_video_title_id_afbdeefd_fk_uploads_vidId; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.multimedia_review
    ADD CONSTRAINT "multimedia_review_video_title_id_afbdeefd_fk_uploads_vidId" FOREIGN KEY (video_title_id) REFERENCES public.uploads("vidId") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_user_id_83bc629a_fk_members_id; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_user_id_83bc629a_fk_members_id FOREIGN KEY (user_id) REFERENCES public.members(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads uploads_cartegory_id_8cad4e6a_fk_cartegories_cartName; Type: FK CONSTRAINT; Schema: public; Owner: aga
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT "uploads_cartegory_id_8cad4e6a_fk_cartegories_cartName" FOREIGN KEY (cartegory_id) REFERENCES public.cartegories("cartName") DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

