
-- Insert data with conflict handling (only adds if id doesn't exist)
INSERT INTO public.auth_permission (id, name, content_type_id, codename)
VALUES
(1, 'Can add log entry', 1, 'add_logentry'),
(2, 'Can change log entry', 1, 'change_logentry'),
(3, 'Can delete log entry', 1, 'delete_logentry'),
(4, 'Can view log entry', 1, 'view_logentry'),
(5, 'Can add permission', 2, 'add_permission'),
(6, 'Can change permission', 2, 'change_permission'),
(7, 'Can delete permission', 2, 'delete_permission'),
(8, 'Can view permission', 2, 'view_permission'),
(9, 'Can add group', 3, 'add_group'),
(10, 'Can change group', 3, 'change_group'),
(11, 'Can delete group', 3, 'delete_group'),
(12, 'Can view group', 3, 'view_group'),
(13, 'Can add content type', 4, 'add_contenttype'),
(14, 'Can change content type', 4, 'change_contenttype'),
(15, 'Can delete content type', 4, 'delete_contenttype'),
(16, 'Can view content type', 4, 'view_contenttype'),
(17, 'Can add session', 5, 'add_session'),
(18, 'Can change session', 5, 'change_session'),
(19, 'Can delete session', 5, 'delete_session'),
(20, 'Can view session', 5, 'view_session'),
(21, 'Can add cartegories', 6, 'add_cartegories'),
(22, 'Can change cartegories', 6, 'change_cartegories'),
(23, 'Can delete cartegories', 6, 'delete_cartegories'),
(24, 'Can view cartegories', 6, 'view_cartegories'),
(25, 'Can add type', 7, 'add_type'),
(26, 'Can change type', 7, 'change_type'),
(27, 'Can delete type', 7, 'delete_type'),
(28, 'Can view type', 7, 'view_type'),
(29, 'Can add videos', 8, 'add_videos'),
(30, 'Can change videos', 8, 'change_videos'),
(31, 'Can delete videos', 8, 'delete_videos'),
(32, 'Can view videos', 8, 'view_videos'),
(33, 'Can add video upload', 9, 'add_videoupload'),
(34, 'Can change video upload', 9, 'change_videoupload'),
(35, 'Can delete video upload', 9, 'delete_videoupload'),
(36, 'Can view video upload', 9, 'view_videoupload'),
(37, 'Can add videos form generator', 10, 'add_videosformgenerator'),
(38, 'Can change videos form generator', 10, 'change_videosformgenerator'),
(39, 'Can delete videos form generator', 10, 'delete_videosformgenerator'),
(40, 'Can view videos form generator', 10, 'view_videosformgenerator'),
(41, 'Can add homepage video', 11, 'add_homepagevideo'),
(42, 'Can change homepage video', 11, 'change_homepagevideo'),
(43, 'Can delete homepage video', 11, 'delete_homepagevideo'),
(44, 'Can view homepage video', 11, 'view_homepagevideo'),
(45, 'Can add members', 12, 'add_members'),
(46, 'Can change members', 12, 'change_members'),
(47, 'Can delete members', 12, 'delete_members'),
(48, 'Can view members', 12, 'view_members'),
(49, 'Can add cart', 13, 'add_cart'),
(50, 'Can change cart', 13, 'change_cart'),
(51, 'Can delete cart', 13, 'delete_cart'),
(52, 'Can view cart', 13, 'view_cart'),
(53, 'Can add deposit history', 14, 'add_deposithistory'),
(54, 'Can change deposit history', 14, 'change_deposithistory'),
(55, 'Can delete deposit history', 14, 'delete_deposithistory'),
(56, 'Can view deposit history', 14, 'view_deposithistory'),
(57, 'Can add download history', 15, 'add_downloadhistory'),
(58, 'Can change download history', 15, 'change_downloadhistory'),
(59, 'Can delete download history', 15, 'delete_downloadhistory'),
(60, 'Can view download history', 15, 'view_downloadhistory'),
(61, 'Can add message', 16, 'add_message'),
(62, 'Can change message', 16, 'change_message'),
(63, 'Can delete message', 16, 'delete_message'),
(64, 'Can view message', 16, 'view_message'),
(65, 'Can add onwatch', 17, 'add_onwatch'),
(66, 'Can change onwatch', 17, 'change_onwatch'),
(67, 'Can delete onwatch', 17, 'delete_onwatch'),
(68, 'Can view onwatch', 17, 'view_onwatch'),
(69, 'Can add password reset', 18, 'add_passwordreset'),
(70, 'Can change password reset', 18, 'change_passwordreset'),
(71, 'Can delete password reset', 18, 'delete_passwordreset'),
(72, 'Can view password reset', 18, 'view_passwordreset'),
(73, 'Can add payment', 19, 'add_payment'),
(74, 'Can change payment', 19, 'change_payment'),
(75, 'Can delete payment', 19, 'delete_payment'),
(76, 'Can view payment', 19, 'view_payment'),
(77, 'Can add buyers', 20, 'add_buyers'),
(78, 'Can change buyers', 20, 'change_buyers'),
(79, 'Can delete buyers', 20, 'delete_buyers'),
(80, 'Can view buyers', 20, 'view_buyers'),
(81, 'Can add group', 21, 'add_group'),
(82, 'Can change group', 21, 'change_group'),
(83, 'Can delete group', 21, 'delete_group'),
(84, 'Can view group', 21, 'view_group'),
(85, 'Can add push information', 22, 'add_pushinformation'),
(86, 'Can change push information', 22, 'change_pushinformation'),
(87, 'Can delete push information', 22, 'delete_pushinformation'),
(88, 'Can view push information', 22, 'view_pushinformation'),
(89, 'Can add subscription info', 23, 'add_subscriptioninfo'),
(90, 'Can change subscription info', 23, 'change_subscriptioninfo'),
(91, 'Can delete subscription info', 23, 'delete_subscriptioninfo'),
(92, 'Can view subscription info', 23, 'view_subscriptioninfo'),
(93, 'Can add notification', 24, 'add_notification'),
(94, 'Can change notification', 24, 'change_notification'),
(95, 'Can delete notification', 24, 'delete_notification'),
(96, 'Can view notification', 24, 'view_notification'),
(97, 'Can add awaiting activation', 25, 'add_awaitingactivation'),
(98, 'Can change awaiting activation', 25, 'change_awaitingactivation'),
(99, 'Can delete awaiting activation', 25, 'delete_awaitingactivation'),
(100, 'Can view awaiting activation', 25, 'view_awaitingactivation'),
(101, 'Can add paymentcodes', 26, 'add_paymentcodes'),
(102, 'Can change paymentcodes', 26, 'change_paymentcodes'),
(103, 'Can delete paymentcodes', 26, 'delete_paymentcodes'),
(104, 'Can view paymentcodes', 26, 'view_paymentcodes')
ON CONFLICT (id) DO NOTHING;
