# Generated by Django 5.1.4 on 2024-12-15 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegories',
            fields=[
                ('cartId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cartName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'cartegories',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('videoId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='movie', max_length=200, verbose_name='Enter Video Name')),
                ('video', models.FileField(upload_to='videos/')),
                ('quality', models.CharField(max_length=100)),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('vidId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('typs', models.CharField(choices=[('movies', 'Movies'), ('series', 'Series'), ('Music', 'Music')], default='movies', max_length=150, verbose_name='video Type')),
                ('synopsis', models.TextField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='videoImage/')),
                ('Quality', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('season', models.CharField(default='season 2', max_length=150)),
                ('popular', models.BooleanField(default=False)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.cartegories', to_field='cartName')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='VideosFormGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('quality', models.CharField(max_length=100)),
                ('name', models.ForeignKey(default='movie', on_delete=django.db.models.deletion.CASCADE, to='multimedia.videoupload', to_field='title', verbose_name='Select Video Name')),
            ],
            options={
                'db_table': 'videosform',
            },
        ),
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.ForeignKey(default='movie', on_delete=django.db.models.deletion.CASCADE, to='multimedia.videoupload', to_field='title', verbose_name='Select Video Name')),
            ],
            options={
                'db_table': 'homepagevideos',
            },
        ),
    ]
