# Generated by Django 5.1.4 on 2025-03-29 13:41

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwaitingActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=100)),
                ('video_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cartegories',
            fields=[
                ('cartId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cartName', models.CharField(max_length=50, unique=True)),
                ('cart_image', django_resized.forms.ResizedImageField(crop=None, default='https://images.unsplash.com/photo-1579713899713-bcd3efe713aa?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', force_format=None, keep_meta=True, quality=-1, scale=None, size=[760, 420], upload_to='cartegories/')),
            ],
            options={
                'db_table': 'cartegories',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('videoId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='movie', max_length=200, verbose_name='Enter Video Name')),
                ('video', models.FileField(upload_to='videos/')),
                ('quality', models.CharField(max_length=100)),
                ('size', models.CharField(default='0mb', max_length=100)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('vidId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('typs', models.CharField(choices=[('movies', 'Movies'), ('series', 'Series'), ('anime', 'Anime')], default='movies', max_length=150, verbose_name='video Type')),
                ('synopsis', models.TextField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[760, 420], upload_to='videoImage/')),
                ('season', models.CharField(default='season 2', max_length=150)),
                ('popular', models.BooleanField(default=False)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='multimedia.cartegories', to_field='cartName')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=150)),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
                ('video_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='multimedia.videoupload')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=150)),
                ('total_like', models.IntegerField()),
                ('video_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='multimedia.videoupload')),
            ],
        ),
    ]
