# Generated by Django 5.1.4 on 2024-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosformgenerator',
            name='name',
            field=models.CharField(default='movie', max_length=200, verbose_name='Enter Video Name'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='image',
            field=models.ImageField(height_field=420, upload_to='videoImage/', width_field=762),
        ),
    ]
