# Generated by Django 5.1.4 on 2024-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_alter_videoupload_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideosFormGenerator',
        ),
        migrations.AddField(
            model_name='videos',
            name='size',
            field=models.CharField(default='0mb', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='typs',
            field=models.CharField(choices=[('movies', 'Movies'), ('series', 'Series')], default='movies', max_length=150, verbose_name='video Type'),
        ),
    ]
