# Generated by Django 5.1.4 on 2024-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_delete_videosformgenerator_videos_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='size',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='size',
            field=models.CharField(default='0mb', max_length=100),
        ),
    ]
